### ISSUE TITLE
Docs for custom metrics

### ISSUE THREAD

**Issue by allevo** [SkeLLLa/fastify-metrics#10]
Hi, thanks for your amazing repo!

I would like to gather some custom metrics but I didn't find some tests that describe this kind of feature. Is it possible to add a custom gauge to prom-client. If yes, how?

I can send you a PR if needed.

**Comment by SkeLLLa** [comment]
Yes, it's possible. Plugin expose `client` which is standard instance of prom-client. So you can use it just as usual prom-client. Try it out `fastify.metrics.client`. If it works, then we can add more detailed docs.

**Comment by wyozi** [comment]
Custom metrics seem to just work when you create them using the FastifyInstance client.

```ts
const socketGauge = new fastify.metrics.client.Gauge({
  name: 'notification_sockets_open',
  help: 'Number of notification websockets open',
  collect() {
    this.set(sockets.length)
  }
})
```

**Comment by petef19** [comment]
see #40  that I just submitted, `labelNames` property currently breaks custom metric registration.
