### ISSUE TITLE
HEAD requests pollute metrics with routes including query parameters

### ISSUE THREAD

**Issue by Sequoia** [SkeLLLa/fastify-metrics#13]
## Reproduction

After this line: https://github.com/SkeLLLa/fastify-metrics/blob/master/src/index.ts#L164 in the `onResponse` hook, add:

```
console.log('context.config.url: ' , context.config.url);
console.log('context.config.statsId: ' , context.config.statsId);
console.log('request.raw.url: ' , request.raw.url);
console.log('routeId: ' , routeId);
```

```
$ curl --get http://localhost/foo/\?x\=1
```

```
$ curl --head http://localhost/foo/\?x\=1
```

## Expected

Last line ('routeId: ') should be `/foo/` **in both cases**

### `GET`

✅

```
context.config.url:  /foo/
context.config.statsId:  undefined
request.raw.url:  /foo/?x=1
routeId:  /foo/
```

### `HEAD`

❌ 

```
context.config.url:  undefined
context.config.statsId:  undefined
request.raw.url:  /foo/?x=1
routeId:  /foo/?x=1
```

# Why this is a problem

This splits up the metrics for the `/foo/` route and creates **thousands** of differently-labeled metrics:

```
http_request_duration_seconds_bucket{le="0.05",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.1",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.5",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="1",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="3",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="5",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="10",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="+Inf",method="HEAD",route="/foo/?x=1",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.05",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.1",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.5",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="1",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="3",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="5",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="10",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="+Inf",method="HEAD",route="/foo/?x=2",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.05",method="HEAD",route="/foo/?x=3",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.1",method="HEAD",route="/foo/?x=3",status_code="200"} 1
http_request_duration_seconds_bucket{le="0.5",method="HEAD",route="/foo/?x=3",status_code="200"} 1
http_request_duration_seconds_bucket{le="1",method="HEAD",route="/foo/?x=3",status_code="200"} 1
http_request_duration_seconds_bucket{le="3",method="HEAD",route="/foo/?x=3",status_code="200"} 1
http_request_duration_seconds_bucket{le="5",method="HEAD",route="/foo/?x=3",status_code="200"} 1
http_request_duration_seconds_bucket{le="10",method="HEAD",route="/foo/?x=3",status_code="200"} 1
http_request_duration_seconds_bucket{le="+Inf",method="HEAD",route="/foo/?x=3",status_code="200"} 1

etc. etc.
```

**Comment by Sequoia** [comment]
Solutions I can think of for this include:

1. Add a `methodsBlacklist` config parameter to drop metrics for methods you don't care about (probably head in most cases)
2. Add an `alwaysStripQuery` config parameter and if set run the `routeId` through a parser once more to ensure query is stripped (seems like overkill/bad perf hit for this, maybe just `.split('?').shift()`
3. If request is `HEAD` do (2) above
4. Add a `makeStatsId(request, reply): string` function to let consumer set their own `statsId` setting logic

(4) is the most flexible assuming it's not some major performance issue.

**Comment by Sequoia** [comment]
Blacklisting is already based on route-without-query: https://github.com/SkeLLLa/fastify-metrics/blob/v6.0.1/src/index.ts#L84

Is there any reason not to make metrics based on this as well? i.e. in `onResponse` hook

```
let routeId = context.config.url || request.raw.url.split('?').shift();
```

**Comment by Sequoia** [comment]
Actually I guess solution (4) above is redundant because consumers can already do that in their route handlers upstream of the `onResponse` hook.

I guess my question is as follows:

**Is it expected/desired behavior that fastify-metrics treat the following as two *separate* routes?**

* `GET /x/?y=1`
* `HEAD /x/?y=1`

My assumption was/is that these **should** produce the same `route` label in metrics. Is this assumption correct?

**Comment by SkeLLLa** [comment]
Basically yes, it should. However since `HEAD` requests usually have no defined `fastfy.head` they don't have context.config.url and fallback to raw request.

So I guess it's safe to introduce `dropUnknownRequests` configuration property or something like that which will filter requests without `context.config.url`.

**Comment by turneand** [comment]
Would the new "invalidRouteGroup" property to bundle all unrecognised urls solve this problem for you?
We had a similar issue where a lot of our endpoints were being probed and ended up with a large number of 404 requests being logged.  But, didn't want to drop them as it's useful to see how many hits we get for invalid endpoints.

**Comment by gugu** [comment]
There are also PROPFIND requests, which can not be handled by fastify, but appear in fastify-metrics

**Comment by SkeLLLa** [comment]
Alongside with other options, now metrics head requests could be disabled with following config option https://github.com/SkeLLLa/fastify-metrics/blob/master/docs/interfaces/plugin.PluginOptions.md#ignoreheadrequests
