### ISSUE TITLE
Can't register plugin multiple times

### ISSUE THREAD

**Issue by StarpTech** [SkeLLLa/fastify-metrics#34]
Hello, currently it's not possible to register the plugin multiple times. An error is thrown by the prom client that the metric was already added. This happening because the plugin uses the global prom registry.

This feature is very valuable for testing.

**Comment by StarpTech** [comment]
This was already covered. It's possible to pass a custom register. Thanks!

```ts
app.register(metricsPlugin, {
  endpoint: '/metrics',
  register: new Registry(),
});
```

**Comment by beautyfree** [comment]
doesn't work with current version and i get error:
```
Error: A metric with the name process_cpu_user_seconds_total has already been registered.
```

**Comment by fatmatto** [comment]
I think the correct usage now is with `clearRegisterOnInit`

```typescript
app.register(fastifyMetrics.default, {
    clearRegisterOnInit: true,
    endpoint: "/metrics"
  })
```
