### ISSUE TITLE
Broken ESM export in v9

### ISSUE THREAD

**Issue by bcomnes** [SkeLLLa/fastify-metrics#49]
Looks like you are double-exporting a default when importing in node esm module mode. 

```
var a = await import('fastify-metrics')
undefined
> a
[Module: null prototype] {
  __esModule: true,
  default: {
    default: <ref *1> [AsyncFunction (anonymous)] {
      default: [Circular *1],
      [Symbol(skip-override)]: true,
      [Symbol(fastify.display-name)]: 'index-auto-0',
      [Symbol(plugin-meta)]: [Object]
    }
  }
}
> 
```

**Comment by SkeLLLa** [comment]
What is the problem here?

```typescript
export default function foo() { }
```

Will result in
```mjs
[Module: null prototype] {
  __esModule: true,
  default: { default: [Function: foo] }
}
```

That's how typescript works. Or I'm missing something?

**Comment by bcomnes** [comment]
I'm not exactly sure what is going on. Usually when importing cjs plugins you can do this:

```js
fastify.register(import('@fastify/basic-auth'), {
  validate,
  authenticate: true
})
```

Instead of this

```js
fastify.register((await import('fastify-metrics')).default, {
    defaultMetrics: { enabled: true },
    endpoint: null,
    name: 'metrics',
    routeMetrics: { enabled: true }
})
```

Looking at the imported objects to compare:

```js
[Module: null prototype] {
  default: <ref *1> [AsyncFunction: basicPlugin] {
    default: [Circular *1],
    '@fastify/basicAuth': [Circular *1],
    [Symbol(skip-override)]: true,
    [Symbol(fastify.display-name)]: '@fastify/basic-auth',
    [Symbol(plugin-meta)]: { fastify: '4.x', name: '@fastify/basic-auth' }
  }
}

[Module: null prototype] {
  __esModule: true,
  default: {
    default: <ref *1> [AsyncFunction (anonymous)] {
      default: [Circular *1],
      [Symbol(skip-override)]: true,
      [Symbol(fastify.display-name)]: 'index-auto-0',
      [Symbol(plugin-meta)]: { fastify: '>=4.0.0', name: 'index-auto-0' }
    }
  }
}
```

I wonder if the named import provides this behavior? I would have to look into it more. I'll reopen if I get a chance to figure out. I've seen a number of ts compiled module that have the `(await import('foo')).default.default` problem, but it looks like its overlapping in a weird way with fastify's plugin system too.

**Comment by SkeLLLa** [comment]
Yes, fastify plugin also add's additional `default`, but this is kind-a recommended way: https://www.fastify.io/docs/latest/Reference/TypeScript/#plugins

Maybe it worth to ask this question if fastify-plugin repo? I'll try to browse other fastify plugins to see how it's done there.
