### ISSUE TITLE
Default labels missing on custom metrics

### ISSUE THREAD

**Issue by kevcodez** [SkeLLLa/fastify-metrics#57]
Default metrics like system CPU have the default label (foo=bar), however, custom metrics like `accountDeleted` do not have the default label, even though it has been registered. As far as I can recall, this used to work with 8.x.

metrics.ts
```ts
import client from 'prom-client';

client.register.setDefaultLabels({foo: 'bar'});

const accountDeleted = new client.Counter({
  name: 'account_deleted',
  help: 'Adds one whenever an account is deleted'
});

export const metrics = {
  accountDeleted,
  defaultLabels,
  register: client.register,
};
```

app.ts
```ts
  await app.register(fastifyMetrics, {
    endpoint: '/metrics',
    defaultMetrics: {
      enabled: true,
      labels: {foo: 'bar'},
      register: metrics.register
    }
  });
```

Result in metrics:

> account_deleted 1
> process_cpu_user_seconds_total{foo="bar"} 3.608122

Expected:

> account_deleted{foo="bar"} 1
> process_cpu_user_seconds_total{foo="bar"} 3.608122

**Comment by kevcodez** [comment]
Furthermore, it seems to be missing on http_request_* metrics, while it is present in process_* and nodejs_* metrics.

Custom label present

> process_cpu_user_seconds_total{foo="bar"} 10.767582
> nodejs_gc_duration_seconds_bucket{le="0.01",kind="incremental",foo="bar"} 6

Missing custom label
> http_request_summary_seconds{quantile="0.01",method="GET",route="/v1/health",status_code="200"} 0.000649474

**Comment by SkeLLLa** [comment]
See https://github.com/siimon/prom-client/issues/143

**Comment by kevcodez** [comment]
@SkeLLLa Is there a way around this as of now, maybe accessing the registries and setting default labels on them, too?

**Comment by SkeLLLa** [comment]
The problem is not in other registries, the problem is basically in merge function. So for now if you have single registry everything will be fine. However for multiple registries proper way is to use `merge`, however it doesn't preserve labels, even if we merge only one registry.

**Comment by kevcodez** [comment]
Worked like a charm.
