### ISSUE TITLE
Include Event Loop Utilization

### ISSUE THREAD

**Issue by mcollina** [SkeLLLa/fastify-metrics#59]
We could include https://nodejs.org/api/perf_hooks.html#performanceeventlooputilizationutilization1-utilization2 to the list of official metrics. A few more explanation reads:

https://nodesource.com/blog/event-loop-utilization-nodejs
https://www.nearform.com/blog/event-loop-utilization-with-hpa/

**Comment by SkeLLLa** [comment]
I think it's better to add this one to [prom-client](https://github.com/siimon/prom-client), so it become available not only in fastify-metrics.
There are already some legacy event loop metrics, but they come from node 4 age.
