### ISSUE TITLE
[bug] Only metrics router can be exposed

### ISSUE THREAD

**Issue by SethWen** [SkeLLLa/fastify-metrics#63]
```
# deps
"fastify": "4.6.0",
"fastify-metrics": "9.2.2",
"prom-client": "14.1.0",
```

`await` must be added when register, or http metrics can not be exposed,  except the metrics router.
The [example.js](https://github.com/SkeLLLa/fastify-metrics/blob/master/examples/example.js) can reproduce this bug, while [example.ts](https://github.com/SkeLLLa/fastify-metrics/blob/master/examples/example.ts) is ok.

**Comment by SkeLLLa** [comment]
Hi. Looks like example was not updated after fastify v4 upgrade, when new register logic was introduced.

Do you want to make a PR with fix?
