### ISSUE TITLE
warning message

### ISSUE THREAD

**Issue by hellower** [SkeLLLa/fastify-metrics#66]
(node:3218427) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.

my fastify version 4.7.0

**Comment by SkeLLLa** [comment]
Hi, that's good find. Do you want to make a PR that will handle this issue?

**Comment by kibertoad** [comment]
I can send a PR tomorrow

**Comment by kibertoad** [comment]
related: https://github.com/fastify/fastify/issues/4347

**Comment by kibertoad** [comment]
This can be fixed after fastify releases next version, but it will break TS builds for older 4.x fastify versions. Would you consider that a semver major?

**Comment by SkeLLLa** [comment]
Fixed in v10. Thanks @kibertoad.
