### ISSUE TITLE
Custom labels

### ISSUE THREAD

**Issue by marcopiraccini** [SkeLLLa/fastify-metrics#74]
Only a predefined set of labels is supported: `method`, `status` and `route`.
Sometimes it would be useful to support "custom" labels set, so that we could:
- Decorate a request with the info we want to get from the label.
- Get the info from the request to populate the custom label. 

This would allow to support more fine-grained metrics.

**Comment by guysegal** [comment]
really +1 for that

**Comment by SkeLLLa** [comment]
Yes, it might be a good feature, wanna work on PR for this?

**Comment by guysegal** [comment]
Yeah I'll try (never actively contributed to open source project before 😅)

**Comment by iamelevich** [comment]
Created PR for this: https://github.com/SkeLLLa/fastify-metrics/pull/80

**Comment by SkeLLLa** [comment]
Looks like this one is resolved. Feel free to reopen if you need something extra.
