### ISSUE TITLE
Passing `enableDefaultMetrics: false` disables the whole plugin

### ISSUE THREAD

**Issue by SimenB** [SkeLLLa/fastify-metrics#8]
`if (enableDefaultMetrics)` wrap the whole plugin, including the hooks

https://github.com/SkeLLLa/fastify-metrics/blob/9aa6453d8e3de787ad41c57eb5d8bf69b98ce666/src/index.ts#L60-L167

**Comment by SkeLLLa** [comment]
Hi. Maybe it requires better description, but originally the meaning of `enableDefaultMetrics` was like to enable prom-client default metrics + enable summary and histogram for each route in fastify.

And if it's disabled, then it just creates client and leaves all the rest to user.

I agree that is confusing, so now is good time to add some breaking changes with upcoming release of fastify v3.

What do you think would be better to do that? With additional flag like `enableRouteMetrics` - enable that histogram and summary and `enableDefaultMetrics` to enable prom-client defaults?

**Comment by SimenB** [comment]
I was expecting the option to disable `prom-client`'s default metrics, not basically make the plugin do nothing but decorate.

What I wanted to do was get the 2 hooks. Getting a router mounted was a nice bonus, but it's like 3 lines of code, so no biggie to do it in our app.

For keeping the current behavior of `enableDefaultMetrics`, I'd think some flag like `onlyDecorate` makes sense?

**Comment by SkeLLLa** [comment]
@SimenB do you need this working in fastify v2? Or making breaking change and publish as a part of new version that supports fastify v3?

**Comment by SimenB** [comment]
Just v3 👍

**Comment by SkeLLLa** [comment]
https://www.npmjs.com/package/fastify-metrics/v/6.0.0-rc.4
`enableDefaultMetrics` - now enables only default prom-client metrics. Set to true by default.
`enableRouteMetrics` - additional flag that enables route metrics. Set to true by default.

**Comment by SkeLLLa** [comment]
Released v6 version, should be fixed in it.
